/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package click.game;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author pujan paudel
 */
public class GameScreen extends javax.swing.JFrame {
    //The Variables Part 
        private int mypoints=0;
        private int x5points=20;
        private int factorypoints=60;
        private int boostpoints=10000;//10 Thousands 
        private static float x5Multiplier=1.5f;
        private static int factoryMultiplier=2;
        private static float pointincrementer=1; // 1 is the Default Multiplier 
        public static GameScreen reference;
        private int multiplier=5;
        private boolean bonusenabled=false;
        
        private int facincreaser=1;
    /**
     * Creates new form GameScreen
     */
    public GameScreen() {
        initComponents();
        reference=this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        click_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        currentpoints = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        x5button = new javax.swing.JButton();
        factory10 = new javax.swing.JButton();
        boostbutton = new javax.swing.JButton();
        plus5value = new javax.swing.JLabel();
        factoryvalue = new javax.swing.JLabel();
        boostprice = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        click_button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        click_button.setText("Click Me !!");
        click_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                click_buttonMouseClicked(evt);
            }
        });
        click_button.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ClickListener(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Click Game");

        currentpoints.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        currentpoints.setText("$0");
        currentpoints.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                currentpointsComponentShown(evt);
            }
        });
        currentpoints.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                currentpointsComponentAdded(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Earning:");

        x5button.setText("+5");
        x5button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                x5buttonMouseClicked(evt);
            }
        });

        factory10.setText("1 Clicks /  10 sec");
        factory10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                factory10MouseClicked(evt);
            }
        });
        factory10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factory10ActionPerformed(evt);
            }
        });

        boostbutton.setText("10% Bonus");
        boostbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boostbuttonMouseClicked(evt);
            }
        });
        boostbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boostbuttonActionPerformed(evt);
            }
        });

        plus5value.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        plus5value.setText("$20");

        factoryvalue.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        factoryvalue.setText("$60");

        boostprice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boostprice.setText("$10,000");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Shop !!!");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Passive Click Generation:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Bumper Purchase");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Points Multiplier");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Pujan Paudel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(click_button, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(currentpoints, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(plus5value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(x5button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(factoryvalue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(factory10, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(boostprice, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(boostbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(12, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(click_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(x5button, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(plus5value)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(factory10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(factoryvalue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(boostbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(currentpoints)
                            .addComponent(jLabel3))
                        .addGap(41, 41, 41)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(boostprice))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boostbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boostbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boostbuttonActionPerformed

    private void ClickListener(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ClickListener
        // TODO add your handling code here:
        
        mypoints+=pointincrementer;
        if(bonusenabled){
                currentpoints.setText("$"+ String.valueOf(mypoints+ (0.1*mypoints)));
        }else{
                            currentpoints.setText("$"+ String.valueOf(mypoints));
        }

    }//GEN-LAST:event_ClickListener

    private void click_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_click_buttonMouseClicked
        // TODO add your handling code here:
        mypoints+=pointincrementer;
        if(bonusenabled){
                currentpoints.setText("$"+ String.valueOf(mypoints+ (0.1*mypoints)));
        }else{
                            currentpoints.setText("$"+ String.valueOf(mypoints));
        }

    }//GEN-LAST:event_click_buttonMouseClicked

    private void currentpointsComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_currentpointsComponentShown
        // TODO add your handling code here:
        System.out.println("Assigning Points");
        currentpoints.setText("$"+ String.valueOf(mypoints));
    }//GEN-LAST:event_currentpointsComponentShown

    private void currentpointsComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_currentpointsComponentAdded
        // TODO add your handling code here:
         System.out.println("Assigning Points");
        currentpoints.setText("$"+ String.valueOf(mypoints)+(0.1*mypoints));
    }//GEN-LAST:event_currentpointsComponentAdded

    private void x5buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_x5buttonMouseClicked
        // TODO add your handling code here:
        System.out.println("We Will Do the talkking");
        if(mypoints<x5points){
    JOptionPane.showMessageDialog(this,
    "Not Sufficient Points to Upgrade ","Warning",JOptionPane.ERROR_MESSAGE);
        }else{
            mypoints-=x5points;
          x5points=(int) (x5points*x5Multiplier);
          plus5value.setText("$" +String.valueOf(x5points));
          pointincrementer+=5;
          multiplier+=2;
           x5button.setText("$ + "+multiplier);
                 currentpoints.setText("$"+ String.valueOf(mypoints));
            JOptionPane.showMessageDialog(this,
    "Enjoy the Upgrade ");
       
        
        
        }
    }//GEN-LAST:event_x5buttonMouseClicked

    private void factory10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factory10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_factory10ActionPerformed

    private void factory10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_factory10MouseClicked
        // TODO add your handling code here:

        if(mypoints<factorypoints){ //Change Here  factorypoints
            JOptionPane.showMessageDialog(this,
                "Not Sufficient Points to Upgrade ","Warning",JOptionPane.ERROR_MESSAGE);
        }else{
            mypoints-=factorypoints;
            factorypoints=factorypoints*factoryMultiplier;
            System.out.println(factorypoints);
           factoryvalue.setText("$" +String.valueOf(factorypoints));
           facincreaser+=3;
                currentpoints.setText("$"+ String.valueOf(mypoints));
           factory10.setText(facincreaser+"clicks"+" / 10 secs");
 JOptionPane.showMessageDialog(this,
    "Enjoy the Upgrade ");
 
            Timer timer=new Timer(1000,new ActionListener() {
//For now Let the Poem Increase test 
                @Override
                public void actionPerformed(ActionEvent e) {
                    mypoints+=facincreaser;
                    currentpoints.setText("$"+ String.valueOf(mypoints));
                }
            });
            timer.setInitialDelay(1000);
            timer.start();
        }
    }//GEN-LAST:event_factory10MouseClicked

    private void boostbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boostbuttonMouseClicked
        // TODO add your handling code here:
        
         if(mypoints<5){//For Now , Test Value 
            JOptionPane.showMessageDialog(this,
    "Not Sufficient Points to Upgrade ","Warning",JOptionPane.ERROR_MESSAGE);
        }else{
          if(boostbutton.isEnabled()){
              boostbutton.setEnabled(false);
           boostprice.setVisible(false);
           bonusenabled=true;
           // Do the Percentage Adding Job !! 
                 currentpoints.setText("$"+ String.valueOf(mypoints));
            JOptionPane.showMessageDialog(this,
    "Enjoy the Upgrade "); 
          }
            
        }
    }//GEN-LAST:event_boostbuttonMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static  void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boostbutton;
    private javax.swing.JLabel boostprice;
    private javax.swing.JButton click_button;
    private javax.swing.JLabel currentpoints;
    private javax.swing.JButton factory10;
    private javax.swing.JLabel factoryvalue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel plus5value;
    private javax.swing.JButton x5button;
    // End of variables declaration//GEN-END:variables
}
    

